openapi: 3.0.3

info: 
  title: my simple app
  description: |
    Using this OpenAPI specification, any conusmer can understand the APIs that are exposed by EazyShop
  termsOfService: https://easzyshop.com/terms/
  contact:
    name: API Support
    url: https://www.eazyshop.com/support
    email: suport@eazyshop.com
  license:
    name: EazyShop License
    url: https://www.eazyshop.com/licenses/LICENSE-2.0.html
  version: 0.0.1

servers:
  - url: https://development.eazyshop-server.com/v1
    description: Development server
  - url: https://staging.eazyshop-server.com/v1 
    description: Staging server
  - url: https://api.eazyshop-server.com/v1
    description: Production server
  - url: https://{username}.server.com:{port}/{version}
    variables:
      username:
        default: demo
        description: This value is assigned by the service provider.
      port:
        enum:
          - "8443"
          - "443"
        default: "8443"
      version:
        default: v1
        
paths: {}